### ISSUE TITLE
Use polymorphic relationship

### ISSUE THREAD

**Issue by thibaultlavoisey** [laravel/airlock#10]
Could be useful for issuing tokens for organization accounts.

**Comment by rennokki** [comment]
I think that a better idea would be the ability to change the Personal Access Token model like Passport: https://laravel.com/docs/5.8/passport#overriding-default-models

It is already in https://github.com/laravel/airlock/pull/18

**Comment by thibaultlavoisey** [comment]
@rennokki Correct me if I'm wrong, changing the personal access token model will allow you to issue token to another model than the user one but not several models, right?

**Comment by rennokki** [comment]
Create a new model `App\MyCustomTokenModel` that extends the base model and replace the `user()` relation:
```php
<?php

namespace App;

use Laravel\Airlock\PersonalAccessToken;

class MyCustomTokenModel extends PersonalAccessToken
{
    public function user()
    {
        // this will be your model
        return $this->morphTo();
    }
}
```

Make use of the function in `boot()`:
```php
use App\MyCustomTokenModel;
use Laravel\Airlock\Airlock;

Airlock::usePersonalAccessTokenModel(
    MyCustomTokenModel::class
);
```

Make sure you ignore the migrations in the `register()` in `AppServiceProvider.php`:
```php
use Laravel\Airlock\Airlock;

Airlock::ignoreMigrations();
```

Publish the migrations or copy the migration file from the package in your `database/migraitons/` folder and replace the `user_id` field with a morph field:
```php
Schema::create('personal_access_tokens', function (Blueprint $table) {
    ...

    $table->morphs('model');

    ...
});
```

In your model (either it's `User`, `Organisation` or whatever) that uses the `HasApiTokens` trait in use, replace the `tokens()` method to make use of the `morphMany`:
```php
use Laravel\Airlock\Airlock;

public function tokens()
{
    return $this->morphMany(Airlock::$personalAccessTokenModel, 'model');
}
```

Jobs done.

**Comment by thibaultlavoisey** [comment]
IMHO it would be simpler that Airlock handle this out of the box using a polymorphic relationship :) Your solution works but it's a bit of extra work for a common use case.

**Comment by rennokki** [comment]
I took Passport's example on this case. I think stuff should be simple out-of-the-box. :male_shrug:

**Comment by socheatsok78** [comment]
I agree to this, I was struggling to customize Laravel Passport to support polymorphic relationship. And I still resolve to use custom HTTP Header hack to get around it.

See laravel/passport#161

**Comment by socheatsok78** [comment]
https://github.com/laravel/passport/issues/1006

**Comment by thibaultlavoisey** [comment]
@taylorotwell Would you accept a PR for this?

**Comment by socheatsok78** [comment]
@taylorotwell 

Thank you kind sir!
👏 👏 👏
