### ISSUE TITLE
CSRF token mismatch when spa is on domain.tld and api on backend.domain.tld

### ISSUE THREAD

**Issue by wassim** [laravel/airlock#100]
I have triple checked the documentation and other users configs here but I can't get my head out of this problem. I spent 2 days debugging but I haven't found any solution.

I have my backend setup on _backend.mydomain.tld_ and my frontend on _mydomain.tld_.

Running an axios get to the airlock/csrf-cookie works just fine and I can see the _XSRF-TOKEN_ set-cookie but when I do a post request afterwards I get an 401 Unauthenticated error because of the X-_XSRF-TOKEN_ and _XSRF-TOKEN_ mismatch.

**Cors.php**

```
return [
    'paths' => [
        'api/*',
        'login',
        'logout',
        'airlock/csrf-cookie'
    ],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true,
];
```

**airlock.php**

```
return [
    'stateful' => explode(',', env('AIRLOCK_STATEFUL_DOMAINS', 'localhost,127.0.0.1,mydomain.tld')),

    ...
```

**session.php**

```
return [
    'driver' => env('SESSION_DRIVER', 'cookie'),
    ...
    'domain' => env('SESSION_DOMAIN', 'mydomain.tld')
    ...
];
```
    
**routes/api.php**

```
Route::middleware('auth:airlock')->group(function () {
    ...
});
```

What the heck am I doing wrong?

**Comment by ianhawes** [comment]
Your default `SESSION_DOMAIN` should be set to '.mydomain.tld'

**Comment by wassim** [comment]
@ianhawes I changed that and flushed the cookies. Still having the same error.

**Comment by ianhawes** [comment]
@wassim Be sure that `AIRLOCK_STATEFUL_DOMAINS` includes `domain.tld,backend.domain.tld`

**Comment by wassim** [comment]
@ianhawes Did that too and cleared config cache. Still the same error 🤷‍♂️

**Comment by Kemel91** [comment]
@wassim add settings server
Access-Control-Allow-Headers "X-XSRF-TOKEN"

**Comment by wassim** [comment]
@Kemel91 the default **Cors.php** config is already handling that.

`'allowed_headers' => ['*'],`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by patrikengborg** [comment]
See [this comment](https://github.com/laravel/sanctum/issues/41#issuecomment-602851087)  for a solution
