### ISSUE TITLE
Call to undefined method Illuminate\\Auth\\TokenGuard::attempt()

### ISSUE THREAD

**Issue by markdark154** [laravel/airlock#101]
- Airlock Version: ^1.9.1
- Laravel Version: ^7.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:
I try to use auth()->attempt(); in my login method and It seems like didn't work. Can you help me to fix this? Thanks a alot.

### Steps To Reproduce:
        auth()->attempt($request->only('email', 'password'));
        return auth()->user();

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
