### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by lionalex** [laravel/airlock#102]
- Airlock Version: 1.0.0
- Laravel Version: 7.0.0
- PHP Version: 7.2.0
- Database Driver & Version: MySql 5.7.23

### Description:
I try login with axios from different domain.
I've the core in "mydomain.com" and the react site in "seconddomain.com".
If I try login from seconddomain.com to mydomain.com with axios API request, it work fine, also without CSRF-COOKIE request.
But If I try to login from my react "localhost:3000" to "mydomain.com", I've "CSRF token mismatch". Why?

This is my configuration:

_in session_
'same_site' => "none",

_axios configuration_
axios.create({
  baseURL: "mydomain.com",
  withCredentials: true,
  responseType: "json",
});

_axios login_
await API.get('/airlock/csrf-cookie');
response = await API.post(
      '/api/v1/login',
      data
);

_cookie from browser - csrf-cooke call_
<img width="1440" alt="Schermata 2020-03-16 alle 14 29 42" src="https://user-images.githubusercontent.com/4151825/76763020-9cb1b700-6792-11ea-84ac-d86dcbdc8978.png">

_cookie from browser - login call_
<img width="1443" alt="Schermata 2020-03-16 alle 14 29 36" src="https://user-images.githubusercontent.com/4151825/76763218-fdd98a80-6792-11ea-907e-e986f436786d.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by alignwebs** [comment]
If anyone is facing CSRF token mismatch issue, then please try checking if `SANCTUM_STATEFUL_DOMAINS=` is set in `.env` 

When `SANCTUM_STATEFUL_DOMAINS` is not present in ENV then it throws CSRF token mismatch error.

Hope it helps someone. :)

**Comment by tbhlabib** [comment]
> 
> 
> If anyone is facing CSRF token mismatch issue, then please try checking if `SANCTUM_STATEFUL_DOMAINS=` is set in `.env`
> 
> When `SANCTUM_STATEFUL_DOMAINS` is not present in ENV then it throws CSRF token mismatch error.
> 
> Hope it helps someone. :)

Thanks alot for this man.. I was looking for this for last 1 hour..

**Comment by AvinFajarF** [comment]
> SANCTUM_STATEFUL_DOMAINS

thanks bro, you have helped me
