### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by klimenttoshkov** [laravel/airlock#103]
- Airlock Version: 1.0.1
- Laravel Version: 7.0.8
- PHP Version: 7.3.13
- Database Driver & Version:
MySQL 5.6.22
### Description:
Airlock is using default database connection to create migration table.
Then If I have multiple users with their own database connection Airlock attempts to insert tokens in users' database connection and not in default connection.

I am not sure if we should have one token table for all users or dedicated token tables for each database connection. 

Based on that we have morphable type in the table I guess we should have one table but it's connection should be specified.

### Steps To Reproduce:
Install and configure airlock on system with multiple database connections. Migrate (it will create table in default db). Authenticate user that is using his own db connection and try to create token.

**Comment by driesvints** [comment]
You can publish the migrations yourself and use `Airlock::ignoreMigrations()` to prevent the migrations from being run.

**Comment by klimenttoshkov** [comment]
You did not understand the issue at all, please reopen so other users may contribute.
—
Kliment Toshkov
mail@klimenttoshkov.com

**Comment by driesvints** [comment]
If you want to provide support for multiple DB connections feel free to send in a PR. We're not planning on doing that ourselves atm.

**Comment by klimenttoshkov** [comment]
I am presenting you with information about bug that not all Authenticatable models work with Airlock.
—
Kliment Toshkov
mail@klimenttoshkov.com

**Comment by jvandop** [comment]
Maybe this will help you:
https://laracasts.com/discuss/channels/laravel/customizing-laravel-sanctum-model?page=1#reply=595153
