### ISSUE TITLE
GraphQL implementation of Airlock

### ISSUE THREAD

**Issue by nckhell** [laravel/airlock#104]
Hi,

I'm building an app where back- and frontend are completely separated. The backend is a GraphQL API built with Laravel and I use Airlock to handle authentication to the frontend app. The frontend is a React application using Apollo as the client.

**The flow of authenticating users (logging in) is clear when using a REST API:**
1. Perform a GET request from the frontend to the backend API via `/airlock/csrf-cookie`. This will set the correct session cookies to be able to log in
2. Perform a POST request with the necessary credentials from the frontend to the backend API  via `/login`. 
3. In the subsequent requests to the backend API I'll be authenticated because I'll have the correct session cookies

This all done by using the predefined GET and POST routes that ship with Laravel/Airlock. Since I'd like to use a 100% GraphQL implementation, I wonder how I can achieve the same functionality but with GraphQL endpoints (Query/Mutation). I'm fairly new at GraphQL and I'm using Lighthouse as the GraphQL server.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
