### ISSUE TITLE
What is the use of axios.get('/airlock/csrf-cookie')?

### ISSUE THREAD

**Issue by smzfreemyt** [laravel/airlock#105]
Hi, why is /airlock/csrf-cookie necessary? Thank you.

Here is full question in stackoverflow: https://stackoverflow.com/questions/60717540/axios-get-airlock-csrf-cookie-doesnt-take-effect-in-laravel-7

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
