### ISSUE TITLE
Support apps without a domain

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/airlock#16]
I saw the domain verification is based on the referer header, but some apps, such as mobile apps, don't have a domain. Maybe the package should support an option to not verify the domain, something like `*` domain.

**Comment by DCzajkowski** [comment]
Doesn't [this](https://github.com/laravel/airlock#authenticating-mobile-applications) solve it for you? Domains are only for stateless browsers, no?

**Comment by lucasromanojf** [comment]
Exactly, as @DCzajkowski said, for mobile apps, you should ignore the stateful stuff and work with the token based authentication.

**Comment by taylorotwell** [comment]
You wouldn't use that approach for mobile apps. You would use personal access tokens.

**Comment by cwilby** [comment]
@taylorotwell is there a recommended approach in Laravel for email verification, while using personal access tokens in a mobile-only environment?
