### ISSUE TITLE
Unable to change route path

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/airlock#17]
By default, the package loads the route into `/airlock/csrf-cookie`.

Since the application constantly accesses only the `/api` routes, I changed the parameter `baseURL` to `axios.defaults.baseURL = '/api';`

Now when you try to send a GET request to address `/airlock/csrf-cookie`, in fact the request is sent to `/api/airlock/csrf-cookie`.

It would be great to do one of the following options:

1. add the ability to specify the route prefix in file `config/airlock.php`;
2. change the route declaration method similar to `Passport::routes()`.

**Comment by Te7a-Houdini** [comment]
@andrey-helldar i think it's implemented now in this [commit](https://github.com/laravel/airlock/commit/ae558c432c207c8a46e3d30e82e6971e23478971)
