### ISSUE TITLE
Using auth's config user model only

### ISSUE THREAD

**Issue by dillingham** [laravel/airlock#19]
Just posing the thought, 

When browsing the code [here](https://github.com/laravel/airlock/blob/master/src/Airlock.php#L35-L51), it looks like if you declare a user model via `useUserModel` that it will only take effect if the `auth.providers.users.model` is null. Which it wouldn't ever be right? 

I wonder if it's safe to assume that `auth.providers.users.model` is always the value desired for this action and that it can bypass the need for the `useUserModel` flexibility you're after.

If removed, maybe the `PersonalAccessToken` model could go in `config/airlock.php`
When someone vendor publishes its all there and don't have to add in a service provider.

Maybe adding the user model to airlock's config too if can't rely on `auth.php` for some reason

**Comment by taylorotwell** [comment]
Fixed.
