### ISSUE TITLE
HasApiTokens tokens() method does not return token

### ISSUE THREAD

**Issue by popica80** [laravel/airlock#25]
In my login controller I am using this code to log in the user 
```
$credentials = $request->only('email', 'password');
        if (Auth::attempt($credentials)) {
            return Auth::user()->tokens()->first();
        }
```
 and the result is like this without the token field:
```
{
    "id": 5,
    "user_id": 6,
    "name": "auth",
    "abilities": [
        "*"
    ],
    "last_used_at": "2020-01-10 18:21:19",
    "created_at": "2020-01-10 18:21:14",
    "updated_at": "2020-01-10 18:21:19"
}
```
Is there something that I missed or mistakenly used?

**Comment by popica80** [comment]
It seems I missed something and had to return it like this:
`return Auth::user()->tokens()->first()->token;`

**Comment by Te7a-Houdini** [comment]
@popica80 can't we just use the latest created tokens instead of using unique ?

**Comment by taylorotwell** [comment]
The tokens are stored hashed in the database. You wouldn't return a token from your login route. I'm honestly not even sure what you are attempting to accomplish here. Are you authenticating your SPA, a mobile app?

<img width="967" alt="image" src="https://user-images.githubusercontent.com/463230/72437144-b8371c00-3767-11ea-86ca-4d9865e786a2.png">
