### ISSUE TITLE
Add configurable token lifetime (like JWT has)

### ISSUE THREAD

**Issue by rcerljenko** [laravel/airlock#30]
It should be a config option for token lifetime (eg. in minutes) and auth guard should automatically reject requests with expired tokens with appropriate status code (401)

**Comment by Te7a-Houdini** [comment]
@rcerljenko i think there's already an expiration [config here that you can set it in minutes](https://github.com/laravel/airlock/blob/master/config/airlock.php#L31)

**Comment by rcerljenko** [comment]
@Te7a-Houdini cool! missed that because i've installed earlier version that didn't have that
i'm just gonna close that issue now  :)

**Comment by francoism90** [comment]
@rennokki @Te7a-Houdini This package isn't JWT compatible right? It may be useful to have additional methods like `refresh()` as this is used by JWT, but I don't know if this is the actual indention of this package? :)
