### ISSUE TITLE
[Question] Why is referer header used instead of getHost()?

### ISSUE THREAD

**Issue by halaei** [laravel/airlock#31]
If I want to support both cookie-based and token based auth, I would dedicate different domans per each auth method, e.g. request to `mysite.com` should be guarded by cookies and sessions and csrf tokens, while request to `myapp.com` should be guarded by bearer token, with no session middleware and csrf token. So I am confused why this project is using referer header instead of `request()->getHost()` or `$_SERVER['HTTP_HOST']`?

**Comment by driesvints** [comment]
Airlock is meant for SPA's and apis and not meant for web based apps. If you need authentication for web based apps, consider using Passport: https://github.com/laravel/passport
