### ISSUE TITLE
Config issue sharing session between web and api

### ISSUE THREAD

**Issue by modstore** [laravel/airlock#34]
Because there's no auth scaffolding to use this at the moment (that I know of anyway), I just left the auth using the standard auth scaffolding.

I ended up having an issue using the session after logging in using the web guard because of my session driver config, it was set to "file" in my .env. I realised that it's set to "cookie" in the Airlock middleware, so once I changed that to match in my .env all was good. But it could be helpful to have a note about this.

**Comment by driesvints** [comment]
Airlock is meant for SPA's and apis and not meant for web based apps. If you need authentication for web based apps, consider using Passport: https://github.com/laravel/passport

**Comment by modstore** [comment]
The rest of my app is SPA, I just left the auth part on the standard web auth scaffolding just to get it going quickly. But no worries if you don't think it's something worth noting.
