### ISSUE TITLE
Method for getting token with specific name

### ISSUE THREAD

**Issue by popica80** [laravel/airlock#37]
I've created a simple method in HasApiTokens.php to get the token with specified name:
```
    public function tokenWithName($name)
    {
        return optional($this->tokens()->where('name', $name)->first())->token;
    }
```
It might be useful when we have multiple tokens with different names for the same user and want to get a specific one.
The problem is the token is the hashed one not the plaint text and it seems it cannot be used to authenticate with route /user when sending the hashed token, it works only with the plain text one, probably because in Guard.php is this line:
`$accessToken = $model::where('token', hash('sha256', $token))->first();`

**Comment by vaibhavpandeyvpz** [comment]
To my understanding, I may authorize same app (with lost state but same name) more than once which would create multiple tokens with same name (in most cases) in which getting which one (by name) cannot be determined.

**Comment by driesvints** [comment]
@vaibhavpandeyvpz you're correct. @popica80 feel free to add this to your own app.

**Comment by let-aurn** [comment]
In my case (with a React Native app), I can set the token's name using the Device ID (see [here](https://github.com/react-native-community/react-native-device-info#getuniqueid)).
And then, before creating a new token, I can just delete the previous one, with the same name.
In my case (a mobile app), It does not make sense for me to have multiple tokens with the same name (for one user).

**Comment by sooxt98** [comment]
@driesvints this is the feature i hope that could exist in this lib :3
https://github.com/laravel/sanctum/issues/177

**Comment by stephan-v** [comment]
For handing out tokens to a mobile application I don't understand why this is not in Sanctum. Every time a user re-authenticates or switches devices they will generate a new token for no reason.
