### ISSUE TITLE
CSRF token mismatch and Unauthenticated

### ISSUE THREAD

**Issue by mbougarne** [laravel/airlock#41]
I can't get it to work with Nuxt in the front-end, firstly I got the **419 ** error number when I tried to access to ```/login``` which is a **CSRF** token issue, I disabled the **CSRF ** token by adding wildcard access in **VerifyCsrfToken Middleware**:
```php
protected $except = [
        '/*',
    ];
```
I passed the login part with that, but I faced another one which is **401 ~ Unauthenticated**: Although I'm in the stateful mode 

Laravel app is running on: ```http://localhost:8000/```
Nuxt app is running on: ```http://localhost:3000/```

I think, there's an issue on ```EnsureFrontendRequestsAreStateful``
My Request using **Axios** as **Nuxt Module**:
```javascript
// I get the cookie [I'm using api as a prefix]
this.$axios.$get('http://localhost:8000/api/csrf-cookie')
// I pass the login
.then(res => {
  this.$axios.$post('http://localhost:8000/login',
  {
    email: this.email,
    password: this.password
  }) 
  // I fail here with 401
  .then( data => {
    this.$axios.$get('http://localhost:8000/api/posts')
    .then( posts => console.log(posts))
  })
})
```

**Comment by danpastori** [comment]
Hi @mbougarne ! I've been trying to solve the same thing. If you visit the thread here: #11 I have all of my steps laid out as well. I think it's something with how Axios sends the cookie.

**Comment by mbougarne** [comment]
Hello @danpastori , It's not an **Axios** issue, I tried with vanilla JS using XHR, besides I disabled the **CSRF** on all routes and I got 401. I start to believe that **Airlock** assumes that the incoming requests are within Laravel application not another provider which is **Vue/Nuxt** in our case. So the SPA is just the front-end part that lives within ```Resources``` folder of **Laravel** App, and if we want to work with Nuxt, Vue-CLI or any front-end as a seperate app we should use ```API Tokens``` Not ```stateful```

**Comment by driesvints** [comment]
I'll leave this to @taylorotwell to investigate.

**Comment by taylorotwell** [comment]
No. Airlock does not require you to put everything in the same app. I've tested it fine with Vue CLI. These are all CORS issues.

**Comment by mbougarne** [comment]
I don't think so, I used [laravel-cors](https://github.com/fruitcake/laravel-cors)

**Comment by monsterdream** [comment]
@mbougarne agree, that same situation here.

**Comment by danpastori** [comment]
I got to this point yesterday and part of it was CORS. However if you are to the point where you are getting a valid 401 response, try changing the SESSION_DRIVER to `cookie` (mentioned in #11). A combination of correct CORS, SESSION_DOMAIN, and SESSION_DRIVER got this resolved.

I managed to get this working with the NuxtJS auth module as well and pushed the code to help out.

Here's my NuxtJS frontend: https://github.com/serversideup/airlock-nuxt-frontend
Here's my Laravel Airlock Backend: https://github.com/serversideup/airlock-laravel-api

I wrote a quick guide to getting them working together focused mainly on NuxtJS frontend with their first class auth module: https://serversideup.net/using-laravel-airlock-with-nuxtjs/. 

If you guys need any help, let me know!

**Comment by SeinopSys** [comment]
I found that I needed the following middleware to get any form of working CSRF with the current instructions as written.

```php
<?php

namespace App\Http\Middleware;

use Closure;

class TransformApiHeaders
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $cookie_name = 'XSRF-TOKEN';
        $token_cookie = $request->cookie($cookie_name);
        if ($token_cookie !== null) {
          $request->headers->add(["X-$cookie_name" => $token_cookie]);
        }
        return $next($request);
    }
}
```

In order for this to work properly the SPA would need to send back the value of the `XSRF-TOKEN` cookie under the request header `X-XSRF-TOKEN`, which currently does not seem to be documented here, but this is how Laravel resolves encrypted CSRF cookies. Reading it from the cookie header like the middleware above does will not protect against CSRF since that cookie is sent along with the request regardless of where it came from, defeating the purpose of CSRF protection entirely.

**Comment by billisonline** [comment]
@SeinopSys your solution worked for me, thanks!

**Comment by SeinopSys** [comment]
@billisonline I sincerely hope that you meant appending the header via JS, otherwise, by adding that middleware in your codebase, you are effectively making CSRF protection pointless.

**Comment by wannymiarelli** [comment]
@SeinopSys Yes, this is what I actually did with fetch. The Laravel doc is clear about how to [send back the CSRF token ](https://laravel.com/docs/5.8/csrf#csrf-x-csrf-token) but yes, I think that would be a good idea to add some kind of reference in the readme.
`
// Check for CSRF token
    let csrf = RegExp('XSRF-TOKEN[^;]+').exec(document.cookie)
    csrf = decodeURIComponent(csrf ? csrf.toString().replace(/^[^=]+./, '') : '')

    if (csrf) {
      headers.append('X-XSRF-TOKEN', csrf)
    }
`

**Comment by steks89** [comment]
@danpastori solution's worked for me
SESSION_DRIVER=cookie (maybe is obvious for some people, but I think it could be in the airlock's documentation),
Also people need to clear cookies before every test.

**Comment by ouhaohan8023** [comment]
I find another reason. If you use Api Token rather than SPA. Your `app/Http/Kernel.php` file  should look like this 
```
'api' => [
//            useless for api token
//            EnsureFrontendRequestsAreStateful::class,
       'throttle:60,1',
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
 ],
```

**Comment by paprotsky** [comment]
AIRLOCK_STATEFUL_DOMAINS=127.0.0.1 in the `.env` file works for me.

**Comment by tranducit95** [comment]
> AIRLOCK_STATEFUL_DOMAINS=127.0.0.1 in the `.env` file works for me.

What?, Why did I fix localhost -> 127.0.0.1 and it worked?

**Comment by tranducit95** [comment]
POST: /api/user: ```message: "Unauthenticated."```
___
My config:
```SESSION_DRIVER=cookie```

```SESSION_DOMAIN=.codeky.local```

```AIRLOCK_STATEFUL_DOMAINS=admin.codeky.local```

```'supports_credentials' => true```

```'paths' => ['api/*', 'login'],```

![DeepinScreenshot_select-area_20200320182335](https://user-images.githubusercontent.com/26267956/77159440-f3432c00-6ad7-11ea-9d3d-eaf439dd1e8e.png)
![DeepinScreenshot_select-area_20200320182318](https://user-images.githubusercontent.com/26267956/77159448-f50cef80-6ad7-11ea-9e0d-665ad732d9cd.png)
![DeepinScreenshot_select-area_20200320182344](https://user-images.githubusercontent.com/26267956/77159453-f5a58600-6ad7-11ea-9852-ccdf70273691.png)

**Comment by patrikengborg** [comment]
I had this problem with getting an "Unauthenticated" error (401) for subsequent requests after a successful login. In my case it was because I made some API requests in `nuxtServerInit` or in the `created` hook. Because of how Nuxt works, those requests are made from the server and not from the client. And I guess the appropriate headers is not included then by default. I found two different solutions.

Make sure the request is made **only** from the client by using:

```
if (process.browser) {
  // Make request
}
```

This can be used in the `created` hook, but won't work in `nuxtServerInit`.

The other solution is to set `proxyHeaders: true` in the axios options. According to the docs:

> In SSR context, this options sets client requests headers as default headers for the axios requests. This is useful for making requests which need cookie based auth on server side. This also helps making consistent requests in both SSR and Client Side code.

I hope this helps someone. I was banging my head for a while, before I figured out what was going on.

@taylorotwell @driesvints I think you would spare yourself a lot of support requests if you added a note about this trap in the docs. Many users seem to be stuck because of this, and think this is a problem with Sanctum, which it's not. Nuxt and Laravel seems to be a popular combo, and it would be a shame if they gave up on using Sanctum because of this.

**Comment by FallenNoir** [comment]
I'm not sure if this is relevant to your particular case, but I encountered a similar issue.
I was receiving 419 while accessing /login straight after successful token request (sanctum/csrf-cookie).
In my case the problem was that Auth::routes() were in web.php, rather than api.php.
Moving the Auth::routes() to api.php fixed the issue to me.

**Comment by incon** [comment]
@FallenNoir  You're required to send back the cookie `XSRF-TOKEN` as a HTTP header `X-XSRF-TOKEN` in the next request.

**Comment by xtrasmal** [comment]
For who has tried this all, followed the instructions etc, see if you are explicitly adding Accept and Content-type headers to every request. For example in custom Middleware. If so, change the priority of the middleware or don't add those headers for this request.

**Comment by kakajansh** [comment]
After trying all of the possible solutions, there is what I come up with, and a bit long checklist for future devs experiencing `401 Unauthorized` and `419 Token mismatch` erros.

Firstly, we should set both apps on same domain. We can use localhost for both, or if we use valet then we can configure reverse proxy for our nuxt app. If you prefer to use localhost, then launch backend app with `php artisan serve` and your backend will be available at `localhost:8000` and frontend at `localhost:3000`. 

I will go with valet, so backend will be `blog.test` and frontend at `front.blog.test`

## Valet setup

```nginx
map $sent_http_content_type $expires {
    "text/html"                 epoch;
    "text/html; charset=utf-8"  epoch;
    default                     off;
}

server {
    listen          127.0.0.1:80;
    server_name     front.blog.test;    # setup your domain here

    gzip            on;
    gzip_types      text/plain application/xml text/css application/javascript;
    gzip_min_length 1000;

    location / {
        expires $expires;

        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_read_timeout                  1m;
        proxy_connect_timeout               1m;
        proxy_pass                          http://127.0.0.1:3000; # set the adress of the Node.js instance here
    }
}

```
## Backend

`/config/auth.php` In my app, I moved from JWT to Sanctum. So need to recheck `auth` file. If you created fresh app then skip this.

```js
'defaults' => [
    'guard' => 'web',
    'passwords' => 'users',
],

'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
    'api' => [
        'driver' => 'token',
        'provider' => 'users',
        'hash' => false,
    ],
],
```

`/config/sanctum.php`
```js
'stateful' => [
    'front.blog.test'
],
```

`/config/cors.php`
```js
'paths' => [
    'sanctum/csrf-cookie',
    'login',
    'api/*'
],
'allowed_methods' => ['*'],
'allowed_origins' => ['*'],
'allowed_origins_patterns' => [],
'allowed_headers' => ['*'],
'exposed_headers' => [],
'max_age' => 0,
'supports_credentials' => true,
```

`/config/session.php`
```js
'driver' => 'cookie',
'domain' => '.blog.test',
'same_site' => 'lax',
```

`/app/Http/Kernel.php` Make sure you have cors
```js
protected $middleware = [
    ...
    \Fruitcake\Cors\HandleCors::class,
];
```

`/routes/api.php` Make sure you use `auth:sanctum` middleware
```php
<?php
Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});
```

## Frontend

`nuxt.config.js`

```js
modules: [
  '@nuxtjs/axios',
  '@nuxtjs/auth'
],

axios: {
  baseURL: "http://blog.test",
  credentials: true   // Attention, credentials not withCredentials
},

auth: {
  redirect: {
    login: '/login',
    logout: '/',
    callback: '/login',
    home: '/'
  },
  strategies: {
    local: {
      endpoints: {
        login: { url: '/login', method: 'post', propertyName: false },
        user: { url: '/api/user', method: 'get', propertyName: false }
      },
      tokenRequired: false,
      tokenType: false
    }
  },
  localStorage: false
},
```

[Using Laravel Sanctum/Airlock with NuxtJS](https://serversideup.net/using-laravel-sanctum-airlock-with-nuxtjs/)
[Authentication in Nuxt.js using Laravel Sanctum](https://swapnil.dev/blog/authentication-in-nuxtjs-using-laravel-sanctum/)

**Comment by ianrussel** [comment]
I also have 419 issue.My react app lives inside rerources.How do you confiigure the sanctum stateful ? my app is laravel-app.test. my backend api is in laravel-app.test/admin/v1/ and the react is in laravel-app.test/admin . I tried what the docs says in sanctum but no luck.

**Comment by Rialga** [comment]
> I find another reason. If you use Api Token rather than SPA. Your `app/Http/Kernel.php` file should look like this
> 
> ```
> 'api' => [
> //            useless for api token
> //            EnsureFrontendRequestsAreStateful::class,
>        'throttle:60,1',
>         \Illuminate\Routing\Middleware\SubstituteBindings::class,
>  ],
> ```

its work for me, thanks !

**Comment by KieronWiltshire** [comment]
This doesn't work for me at all, I've created an API where multiple front-ends on different domains contact the API, however I wanted them all to be stateful. So I dynamically return stateful domains from my DB like so, but this is being blocked by CORS somehow and I can't figure out why...

```php
<?php

namespace App\Http\Middleware;

use App\Http\Concerns\RetrievesBrandFromRequest;
use Domain\Brand\Exceptions\ValidBrandRequiredException;
use Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful as SanctumEnsureFrontendRequestsAreStateful;

class EnsureFrontendRequestsAreStateful extends SanctumEnsureFrontendRequestsAreStateful
{
    use RetrievesBrandFromRequest;

    /**
     * Determine if the given request is from the first-party application frontend.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    public static function fromFrontend($request)
    {
        $brand = false;

        try {
            $brand = static::fromReferer();
        } catch (ValidBrandRequiredException $e) {}

        return ($brand || parent::fromFrontend($request)) ? true : false;
    }
}
```

**Comment by damdiaz** [comment]
## Configuragtion
In `.env` file
```
...
CLIENT_URL=client.test.localhost
SESSION_DOMAIN=.test.localhost
...
```

`config/sanctum.php`
```
'stateful' => [
    env('CLIENT_URL')
],
```

`config/cors.php`
```
   'paths' => [
        'api/*',
        'sanctum/csrf-cookie',
        'login',
        'logout'
    ],

    'allowed_methods' => ['*'],

    'allowed_origins' => [env('CLIENT_URL')],

    ...

    'allowed_headers' => ['*'],

    ...

    'supports_credentials' => true
```
## Backend Application
`app/Http/Kernel.php`
```
   protected $middleware = [
        ...
        \Fruitcake\Cors\HandleCors::class,
       ...
    ];
   protected $middlewareGroups = [
        ...
        'api' => [
            EnsureFrontendRequestsAreStateful::class,
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

`routes/web.php`
```
...
Route::post('login', 'Auth\LoginController@login')->name('login');
...
```

`routes/api.php`
```
...
Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});
...
```

## Client Application
`.env`
```
API_URL=api.test.localhost
```

`nuxt.config.js`
```
...
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth-next'
  ],
...
  auth: {
    strategies: {
      cookie: {
        cookie: {
          name: 'X-XSRF-TOKEN'
        }
      },
      laravelSanctum: {
        provider: 'laravel/sanctum',
        url: process.env.API_URL
      }
  }
```
The name for the cookie must be set to `X-XSRF-TOKEN` and not `XSRF-TOKEN`

**Comment by ryoyin** [comment]
> I find another reason. If you use Api Token rather than SPA. Your `app/Http/Kernel.php` file should look like this
> 
> ```
> 'api' => [
> //            useless for api token
> //            EnsureFrontendRequestsAreStateful::class,
>        'throttle:60,1',
>         \Illuminate\Routing\Middleware\SubstituteBindings::class,
>  ],
> ```

you saved my day. I tried 3 hours to make it work.

**Comment by andreladocruz** [comment]
We run our applications in google app engine with 2 different services: default (laravel) and myorders (nuxt)

MyOrders services call the laravel API and we use sanctum.

You can try it here: https://dev.digitalmanager.guru/myorders/

When the user fills the email and click to send, we call the https://dev.digitalmanager.guru/sanctum/csrf-cookie URL and the cookie is corrected created:

![image](https://user-images.githubusercontent.com/3315596/113351473-d704dc80-9332-11eb-9a1c-17fed5268e74.png)

After we send a post request to send the user email and got a token mismatch error:

![image](https://user-images.githubusercontent.com/3315596/113351571-fbf94f80-9332-11eb-9a4d-8e9f4601963e.png)

Even with the X-XSRF-TOKEN correctly sent:

![image](https://user-images.githubusercontent.com/3315596/113351664-17645a80-9333-11eb-990e-dd7638003c63.png)

@taylorotwell, can you help us find the solution?

**Comment by andreladocruz** [comment]
@taylorotwell,

Digging deeper I found the reason for the token mismatch error.

When using redis sessions, the getTokenFromRequest from Illuminate\Foundation\Http\Middleware\VerifyCsrfToken returns something like this "30995|DDjAe5opsd7urpwrpwJLEvlFePuLmvEdXHNlr00e";" while the $request->session()->token() returns something like this "DDjAe5opsd7urpwrpwJLEvlFePuLmvEdXHNlr00e".

So, when the "hash_equals($request->session()->token(), $token)" command returns false.

I added the following block of code to App\Http\Middleware\VerifyCsrfToken and it worked

![image](https://user-images.githubusercontent.com/3315596/113380535-68487300-9374-11eb-965b-7bc32bfd45e9.png)

**Comment by alignwebs** [comment]
If anyone is facing CSRF token mismatch issue, then please try checking if `SANCTUM_STATEFUL_DOMAINS=` is set in `.env` 

When `SANCTUM_STATEFUL_DOMAINS` is not present in ENV then it throws CSRF token mismatch error.

Hope it helps someone. :)

**Comment by kennyuzoma** [comment]
@alignwebs wow this actually worked

**Comment by ToNyRANDRIAMANANTSOA** [comment]
For my case, the cause of the CSRF token mismatch was that I have multiple host names  (other than localhost) pointing to 127.0.0.1 set on my local machine, and `reactscripts` started the development server to the other hostname.
Changing it back to localhost solved the issue :)

**Comment by benounnas** [comment]
it may seem obvious, but as developers we learn from mistakes to improve.
like @ToNyRANDRIAMANANTSOA  mentioned, i had a smiliar issue where  the frontend client was pointing to `http://127.0.0.1:8000` rather than `http://localhost:8000` where my `SESSION_DOMAIN=localhost` and `SANCTUM_STATEFUL_DOMAINS=localhost:8086` (quasar).
thank you !

**Comment by walteranyika** [comment]
I encountered the same issue when using `localhost` domain, but when I switched to a **`valet`** domain like `app.test`, everything worked perfectly.

**Comment by peshr4w** [comment]
> I found that I needed the following middleware to get any form of working CSRF with the current instructions as written.
> 
> ![Don't try this at home](https://user-images.githubusercontent.com/3200580/73110427-a5121200-3f06-11ea-8839-96bcb6175f15.png)
> 
> Reading the token from the cookie header like the middleware above does will not protect against CSRF since that cookie is sent along with the request regardless of where it came from, defeating the purpose of CSRF protection entirely.
> 
> In order for this to work properly the SPA would need to send back the value of the `XSRF-TOKEN` cookie under the request header `X-XSRF-TOKEN`, which currently does not seem to be documented here, but this is how Laravel resolves encrypted CSRF cookies.

where is this file?

**Comment by victorsiqueira14** [comment]
If you are using JWT. I commented this line in the kernel and it worked!

![Screenshot 2023-11-08 at 10 01 36](https://github.com/laravel/sanctum/assets/79598885/a558426b-1c28-419f-8610-0a20957a1344)

**Comment by ArifulSikder** [comment]
> > I found that I needed the following middleware to get any form of working CSRF with the current instructions as written.
> > ![Don't try this at home](https://user-images.githubusercontent.com/3200580/73110427-a5121200-3f06-11ea-8839-96bcb6175f15.png)
> > Reading the token from the cookie header like the middleware above does will not protect against CSRF since that cookie is sent along with the request regardless of where it came from, defeating the purpose of CSRF protection entirely.
> > In order for this to work properly the SPA would need to send back the value of the `XSRF-TOKEN` cookie under the request header `X-XSRF-TOKEN`, which currently does not seem to be documented here, but this is how Laravel resolves encrypted CSRF cookies.
> 
> where is this file?



Is this process secure?

**Comment by kennyalmendral** [comment]
Here's the `.env` config that worked for me:

```
APP_URL=https://api.example.com
FRONTEND_URL=https://app.example.com

SESSION_DOMAIN=".example.com"
SANCTUM_STATEFUL_DOMAINS=app.example.com

# SESSION_DRIVER=database
SESSION_DRIVER=cookie
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
# SESSION_DOMAIN=null
```
