### ISSUE TITLE
Consider unique constraint on `user_id` and `name`

### ISSUE THREAD

**Issue by MikeGlennFWC** [laravel/airlock#42]
I feel there is a benefit to adding a unique constraint across the columns **user_id** and **name**.

Currently users can create multiple tokens with the same name, meaning differentiating between them at a later date would be impossible as the key is only to be shown **once**.

**Comment by driesvints** [comment]
Duplicate of https://github.com/laravel/airlock/issues/25

**Comment by MikeGlennFWC** [comment]
Can this be reviewed again, #25 has been closed on the first issue.

**Comment by driesvints** [comment]
@MikeGlennFWC we won't be enforcing this through the library. You can implement this yourself in your app if you want.
