### ISSUE TITLE
Question: is there a reason that session.driver is forced to cookie?

### ISSUE THREAD

**Issue by ryzr** [laravel/airlock#43]
A teammate and I were stumped as to why the session from our web-based login was not available when making API requests with the provided middleware. After awhile, we realised that our session driver was set to database (which is preferable to us), and the middleware enforces the cookie driver.

Simply removing the session.driver = cookie section from the middleware works, but I'm assuming there is a reason it is set up this way? To my understanding, the session id is stored as an encrypted cookie anyway (withEncryptCookies and StartSession middleware in the pipeline), and it's simply the data stored within the session that is affected by the `configureSecureCookieSessions` method.

Any thoughts?

**Comment by ryzr** [comment]
@smcassar

**Comment by taylorotwell** [comment]
There is not a technical reason, I just figured if people were building an API backed SPA that it was a sensible default and you wouldn't want to have to worry about server backed session storage. I can change it if there is enough demand.
