### ISSUE TITLE
How save token in browser

### ISSUE THREAD

**Issue by hamedcode** [laravel/airlock#44]
Hello,
Before everything we are happy that @taylorotwell make this package.

1.After i use airlock for login it redirect to `/home` which is incorrect and i wanto redirect to `$redirectTo`.
2.Should we save token in localstoeage? 
3.How can i send Bearer to server?

@taylorotwell I think we need full example for this package.

**Comment by juretopolak** [comment]
Saving token in the local storage is not the best practice:
https://dev.to/rdegges/please-stop-using-local-storage-1i04

I would also like to see an example of how to send Bearer...  I was just playing around with auth in SPA, where login was successful, a token was also saved in the 'personal_access_tokens' table.

What I didn't figure out jet is how to make a successful request on a protected route. What is the correct key name of the parameter (token) in the post / get request? I have tried apiToken, token, api-token... nothing works.

```
Route::middleware('auth:airlock')->post('/user', function (Request $request) {
    return $request->user();
});
```

All requests on http://airlock.test/api/user are redirected to /login.

What am I missing here? :)

**Comment by taylorotwell** [comment]
You don't send any token at all. You don't use personal access tokens at all for accessing a SPA. Please consult the README:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/463230/72437028-74441700-3767-11ea-8195-1afd42037795.png">

**Comment by hirenkeraliya** [comment]
The same issue But, I have SPA application in a different origin like our server API URL has the `homestead.test` and the spa URL is the `latest-laravel.test` then it's not working so how can I pass the token to the server?

**Comment by evansmwendwa** [comment]
The package documentation makes it very clear that it's targeted for first party apps hosted on the same domain name.

For apps in different domain I would suggest creating a proxy app that handles the authentication and sets the cookie (practically what airlock is doing but for your other domain) otherwise Laravel Passport should be the go to for that case

**Comment by auctionsoftware** [comment]
Hello @taylorotwell,
sanctum is working fine with POSTMAN but when I am trying to call that API from browser without token it doesn't give me an error it allows me to fetch all the data

can please help me out this problem

Thank you

**Comment by hirenkeraliya** [comment]
Yes,  but where I store the barrier token. and I have no possibilities to store the cookie. because it's a widget application.
