### ISSUE TITLE
Airlock with Cookie Token HttpOnly

### ISSUE THREAD

**Issue by janisii** [laravel/airlock#45]
In most cases for SPAs, it's not recommended to store token in `localStorage` for sending token to API server with Bearer authorization header for security issues. 

Would you consider to add extra check for cookie token in `airlock/Guard.php` to check if headers contains valid token in cookie which is set as `HttpOnly`.

The response sent from controller's `login` method could be this:

    return response()
       ->json(['success' => 'User logged.'], 200)
       ->withCookie(cookie(config('airlock.cookie_token_name'), $token, $minutes)); 
 
Next request to API server would automatically include the token to access protected routes with `auth:airlock` middleware. 

Sorry, if it's totally not relevant at all here and have misunderstood the idea behind `airlock`.

**Comment by taylorotwell** [comment]
Why are people sending tokens from localStorage? I don't understand this at all. Airlock DOES NOT use tokens at all when you are interacting with it from your SPA. It uses normal Laravel session cookies. The tokens are ONLY used when sharing a token with a third-party, like a mobile application or some other service entirely.

**Comment by janisii** [comment]
> The tokens are ONLY used when sharing a token with a third-party, like a mobile application or some other service entirely.

Thanks, this makes things clear. For those who struggle to authenticate from SPA, use default login route from `php artisan ui:auth`.

Simple code snippet to test if auth is successful from SPA.

    ...
    const handleLogin = async () => {
        await axios.get('/airlock/csrf-cookie');
        await axios.post('/login', { email: 'email@test.com', password: 'pass1234' });
        const res = await axios.get('/api/user');
        console.log(res.data);
    };

    return (
        <button onClick={handleLogin}>Log In</button>
    );
    ...

And double check if you haven't accidentally opened your SPA from IP address `http://127.0.0.1:8000` must be changed to `http://localhost:8000` for airlock to work.

**Comment by ianrussel** [comment]
> Why are people sending tokens from localStorage? I don't understand this at all. Airlock DOES NOT use tokens at all when you are interacting with it from your SPA. It uses normal Laravel session cookies. The tokens are ONLY used when sharing a token with a third-party, like a mobile application or some other service entirely.

@taylorotwell , Thanks for this  wonderful package and the hardwork. Might be good if it work also in Safari browsers.
