### ISSUE TITLE
Suggestion: Adding a token timeout configuration option

### ISSUE THREAD

**Issue by enygma** [laravel/airlock#5]
I briefly looked through the code and didn't see anything that indicated that the tokens from this were ever expired. The problem with not expiring the tokens is that, if they were ever somehow captured (maybe an XSS in the site or some man-in-the-middle), they would work forever.

I'd suggest implementing some kind of default timeout on the tokens that the user could adjust to their liking. I can understand the argument of "the developer should invalidate the token when they choose too" but that's not a secure by default approach. Given that this is a security control, I'd recommend at least allowing this kind of value to be set.

**Comment by taylorotwell** [comment]
I assume you are referring to the tokens generated by `createToken`? I would be fairly open to this. I don't really have a strong preference either way. They are originally designed to work like GitHub personal access tokens which never expire.

**Comment by enygma** [comment]
I can understand that perspective. I think these are a bit different use case than those tokens, though. Application sessions are usually designed to be short-lived versus the GH tokens that are designed to be a long-lived token where there's no "refresh" ability. In the case of this library, it looks like it's somewhat mimicking an OAuth structure which includes a timeout for exactly this purpose.

I see there's already a "last used" column in the table. This could be used along with the "timeout" configuration option to check for the validity of the token. Ideally it'd be based on the token creation time, but that's adding even more functionality to the mix.

So, say you add a default config option for the default timeout to be something reasonable for most user interactions, like 2 hours. Then the guard could check the last used+timeout values and see if it's valid or not. That wouldn't require many changes to the current functionality and would help reduce the risk of tokens being valid forever.

**Comment by enygma** [comment]
I'd also include something in the documentation for this feature about how to revoke tokens (just deleting them, I assume) so users are aware they can kill off user sessions at will. This is much easier than if they were JWT tokens, fortunately.

**Comment by usmanfourspan** [comment]
Yes, there should be timeout feature for expiring the token.

**Comment by DCzajkowski** [comment]
It would be cool if the _generation_ and _verification_ processes were abstracted in a class with an interface so that Airlock could be extended by third parties with other token implementations (like JWT). This way Airlock's way would be:
```
class AirlocksWay extends TokenIssuerAndVerifier
  generate()
    // randomize
    // store in db etc.

  verify()
    // get from db
    // etc.
```
and
```
class JWTWay extends TokenIssuerAndVerifier
  generate()
    // generate the token as JWT

  verify()
    // verify as JWT
```
This way if someone wants to use a token that has timeouts, they'd create their own implementation of TokenIssuerAndVerifier. If they wanted JWT — same thing.

I do not know how possible that is in current implementation as I haven't had much time to look through the code.

**Comment by taylorotwell** [comment]
Done.

**Comment by taylorotwell** [comment]
@enygma added a timeout, but note those tokens are *not used* for application sessions. Normal session cookies are... these are only used for third-party API access.
