### ISSUE TITLE
Airlock::actingAs

### ISSUE THREAD

**Issue by leemcd56** [laravel/airlock#50]
I would really like to use this as an alternative to Passport for an API I am building, but a lot of my tests use `Passport::actingAs` for roles and permissions tests.

How could one go about mocking this functionality for the time being so I could write in tests like this:

```php
   /**
     * Test DELETE /api/properties/{id}.
     *
     * @return void
     */
    public function testDeleteProperty()
    {
        Airlock::actingAs(
            factory(\App\User::class)->create()->attachRole('admin')
        );

        $property = factory(\App\Property::class)->create();
        $response = $this->deleteJson('/api/properties/' . $property->id);

        $response
            ->assertOk()
            ->assertJsonPath('message', 'Deleted property.');

        $this->assertSoftDeleted('properties', [
            'id' => $property->id,
        ]);
    }
```

**Comment by driesvints** [comment]
Feel free to attempt a PR.

**Comment by Te7a-Houdini** [comment]
@leemcd56 i have a quick question . does ``` $this->actingAs($user)``` can solve the case ?

**Comment by leemcd56** [comment]
> @leemcd56 i have a quick question . does ` $this->actingAs($user)` can solve the case ?

@Te7a-Houdini It doesn't create a new personal access token to provide the proper access.

I have opened up PR #51 to add in `::actingAs`. I am having an issue creating a new token because, even though migrations are running, the `personal_access_tokens` table does not appear to exist during the test.

**Comment by Te7a-Houdini** [comment]
Got it thanks for the clarification

**Comment by driesvints** [comment]
PR was merged
