### ISSUE TITLE
Adding additional data to createToken

### ISSUE THREAD

**Issue by dillingham** [laravel/airlock#55]
Idea: adding a 3rd parameter to `createToken()` for custom columns

If your token has additional scope or tenant information.. being able to pass it in like:
```php
createToken('token-name', ['*'], ['tenant_id' => 1'])
```
With an array merge.. would be convenient 
```php
$token = $this->tokens()->create(array_merge([
    'name' => $name,
    'token' => hash('sha256', $plainTextToken = Str::random(80)),
    'abilities' => $abilities,
], $values);
```

Otherwise, an observer works or `$token->update($values)` on the returned token

**Comment by dillingham** [comment]
or maybe the first parameter could be string or callable.

```php
createToken(function($token) {
    $token->name = 'Name';
    $token->tenant_id = 1;
}, $abilities);
```

```php
$token = new Token;
$callable($token);
$token->token = hash()
$token->save();
```

**Comment by dillingham** [comment]
`makeToken()`  is probably more laravel like though and it returns unsaved model

**Comment by driesvints** [comment]
You're mentioning a tenant ID. Isn't it just the case of adding the `HasApiTokens` trait to different tenant types? Do you need to query/purge per tenant ID? How would the data be saved?

**Comment by dillingham** [comment]
I was just using the tenant id as a vague example. You’re right you can just attach the token to the tenant. 

Mostly was just suggesting a way to add data to the token without having to update it after create. 

JWT sometimes you add data sometimes

**Comment by cja-github** [comment]
Hi. I need this. Has it been implemented?

**Comment by minhlong** [comment]
Hi,

I have the same problem, hope that it will be updated.

Thanks,

**Comment by dan-lutd** [comment]
@minhlong Did this work for you?   How would a token holder read the 'shop_id' from the token?

**Comment by minhlong** [comment]
> @minhlong Did this work for you? How would a token holder read the 'shop_id' from the token?

The shop_id is used to create token. It does not use to validate the token :). You can refer below flow:

```
# \Laravel\Sanctum\PersonalAccessToken
/**
     * Find the token instance matching the given token.
     *
     * @param  string  $token
     * @return static|null
     */
    public static function findToken($token)
    {
        if (strpos($token, '|') === false) {
            return static::where('token', hash('sha256', $token))->first();
        }

        [$id, $token] = explode('|', $token, 2);

        if ($instance = static::find($id)) {
            return hash_equals($instance->token, hash('sha256', $token)) ? $instance : null;
        }
    }
```

**Comment by teclia** [comment]
Excelent! Thanks for posting. I used your example and it worked for me

**Comment by dan-lutd** [comment]
@minhlong  I see the shop_id is only added to the table via PersonalAccessToken, thanks
