### ISSUE TITLE
Front-end requests on unknown third-party domains

### ISSUE THREAD

**Issue by KieronWiltshire** [laravel/airlock#57]
I have a backend API running on a subdomain `api.example.com` but then I have multiple front-ends, all which call the same API but are under different domains, some of which are not first party.

Is it possible to have some way of having third party applications request to use stateful authentication?

I was thinking of maybe having some form of callback which returns the valid urls [here](https://github.com/laravel/airlock/blob/master/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php#L63). I would be able to then return which referers are stateful and which ones arent dynamically.

I guess I could just extend the middleware and overwrite the `fromFrontend` method, hmmm

It would also be a great idea to add some form of helper method to determine if the request is coming from any of the stateful referrers, as my current /auth/login returns the auth token, and since I'm not using it in my front-ends I don't see any point in returning it.

**Comment by KieronWiltshire** [comment]
I currently do it like this, but I'm not sure if this is the best way to do it...
```php
<?php

namespace App\Http\Middleware;

use App\Http\Traits\RetrievesBrandFromReferer;
use Laravel\Airlock\Http\Middleware\EnsureFrontendRequestsAreStateful as AirlockEnsureFrontendRequestsAreStateful;

class EnsureFrontendRequestsAreStateful extends AirlockEnsureFrontendRequestsAreStateful
{
    use RetrievesBrandFromReferer;

    /**
     * Determine if the given request is from the first-party application frontend.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    public static function fromFrontend($request)
    {
        return (static::retrieveBrand(true) || parent::fromFrontend($request)) ? true : false;
    }
}
```

**Comment by driesvints** [comment]
Does either https://divinglaravel.com/authentication-and-laravel-airlock or the discussion on https://github.com/laravel/airlock/issues/11 help? Did you search the issue tracker to help you?

**Comment by KieronWiltshire** [comment]
@driesvints I did and couldn't find my answer, so basically what I'm saying is, there is a case for providing stateful authentication dynamically which I had to retro fit by overriding the "fromFrontend" function inside the `EnsureFrontendRequestsAreStateful` middleware.

**Comment by driesvints** [comment]
_Why_ do you want stateful authentication for these?

**Comment by KieronWiltshire** [comment]
@driesvints we provide an API to our customers and manage everything on our customers behalf, however they're in charge of their front-end/branding/marketing etc... so in our case specifically, we offer a backend and they create their own front-end which uses our system under the hood if that makes sense?

**Comment by driesvints** [comment]
I don't think anything stateful is wanted for third-party apps. Like the docs say you'll only want those to auth using tokens: https://github.com/laravel/airlock#attaching-the-authentication-guard

> or contain a valid API token header if the request is from a third party:

**Comment by KieronWiltshire** [comment]
It's more to the point that we license this software out, and businesses have their own front-end created on top of a template we've created (they pay us or someone to style it)

They create multiple front-ends that may be on different domains and manage the application themselves. So we have a database table which they can just input any new domains they add

**Comment by driesvints** [comment]
@KieronWiltshire in that case I think overwriting the middleware is twtg.

**Comment by smtlab** [comment]
So the documentation says this

Protecting Routes

To protect routes so that all incoming requests must be authenticated, you should attach the sanctum authentication guard to your API routes within your routes/api.php file. This guard will ensure that incoming requests are authenticated as either a stateful authenticated requests from your SPA **or contain a valid API token header if the request is from a third party**:
