### ISSUE TITLE
usePersonalAccessTokenModel more described

### ISSUE THREAD

**Issue by renege** [laravel/airlock#60]
Hello,

This is in the docs:

> ## Customization
> You may customize the personal access token model used by Airlock via the usePersonalAccessTokenModel methods. Typically, you should call this method from the boot method of your AppServiceProvider:
> ```
> use App\Airlock\CustomPersonalAccessToken;
> use App\CustomUser;
> use Laravel\Airlock\Airlock;
> 
> public function boot()
> {
>     Airlock::usePersonalAccessTokenModel(
>         CustomPersonalAccessToken::class
>     );
> }
> ```

Looks promising, because in that way you can use a different Model then ```App/User``` for requests made with the Airlock Middleware, but the example is incomplete.. 

My expectation is when you got the ```usePersonalAccessTokenModel``` to work with a different custom Model that will result as the request()->user. 

This code:
```
Route::middleware(‘auth:airlock’)->get(‘/name’, function (Request $request) {
    $user = $request->user(); // Expected Model to be: App\CustomUser
    return response()->json([‘name’ => $user->name]);
});
```
I expect that the ```$user``` is of a Model-type: ```App\CustomUser```, but it isn't.

**Comment by rcubitto** [comment]
The `PersonalAccessToken` is the model that represents a token, not a user. In fact, a user can have many tokens. These are 2 different models.
