### ISSUE TITLE
1 guard for all?

### ISSUE THREAD

**Issue by KieronWiltshire** [laravel/airlock#64]
- Airlock Version: 0.1.0
- Laravel Version: 6.13.1
- PHP Version: 7.3.9
- Database Driver & Version: MySQL

### Description:
When using airlock as a guard, it assumes that guard on non-auth required routes. The issue with this is that when wanting to fallback on passport, it's impossible. 

The issue I present is that I'm using passport for my bearer tokens and airlock for my session authentication. Airlock sits at the front, and if it fails to find what it needs, I'd like it to then check the passport guard.

Possible solution: fallback to desired guard if session is not found.

**Comment by taylorotwell** [comment]
Share your route definition.

**Comment by KieronWiltshire** [comment]
I solved the issue by creating this middleware and adding it to the "api" group.

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Http\Request;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Support\Exceptions\Auth\AuthenticationRequiredException;

class EnsureFallbackAuthGuard extends Middleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    public function handle($request, Closure $next, ...$guards)
    {
        $this->authenticate($request, ['api', 'airlock']);

        return $next($request);
    }

    /**
     * Determine if the user is logged in to any of the given guards.
     *
     * @param \Illuminate\Http\Request $request
     * @param array $guards
     * @return void
     */
    protected function authenticate($request, array $guards)
    {
        try {
            parent::authenticate($request, $guards);
        } catch (AuthenticationException $e) {}
    }
}
```

it essentially forces this:
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/Middleware/Authenticate.php#L63

**Comment by taylorotwell** [comment]
Unnecessary. You don’t need this to do what you want to do. It’s already built into Laravel. If you want to share your original route definition go ahead.

**Comment by KieronWiltshire** [comment]
@taylorotwell I don't believe it checks all guards for non-auth routes though right? I'll try show example:

```php
/**
     * Brand routes
     */
    Route::name('brand.')->prefix('brand')->middleware('auth:api,airlock')->group(function () {
        Route::get('/', 'BrandController@index')->name('index'); // This checks "api" guard but fallsback to "airlock"
    });

    /**
     * User routes
     */
    Route::name('user.')->prefix('user')->group(function () {
        Route::get('/', 'UserController@index')->name('index'); // This only checks "api" guard
    });
```

**Comment by taylorotwell** [comment]
If you feel there is broken behavior send a PR with a fix and a test.

**Comment by rickshawhobo** [comment]
I have this same problem. A possibly fix is to allow the auth config to take the same guard array. Something like
```
    'defaults' => [
        'guard' => 'web,api',
        'passwords' => 'users',
    ],
```

Your workaround isn't too bad @KieronWiltshire
