### ISSUE TITLE
Handling for when Accept header not passed

### ISSUE THREAD

**Issue by narwy** [laravel/airlock#72]
- Airlock Version: Latest
- Laravel Version: Latest
- PHP Version: 7.4 FPM
- Database Driver & Version: MySQL 8

### Description:
Is there a better way to handle this route not found error 500 issue.

If I have a route:
```
Route::middleware('auth:airlock')->get('/user', function (Request $request) {
    return $request->user();
});
```
Then let's say a random user visits `/user` not in the "api calling way" of the SPA passing the header, surely we don't want to throw a 500 error by default? There must be a better way to handle this to return another form of error. 500 status code doesn't suffice and obviously I don't have a login page/route by default.

### Steps To Reproduce:
`Route [login] not defined` thrown when the `Accept` header is not passed as `application/json` (Yes it would and should be passed like this).

### Flare Trace:
https://flareapp.io/share/353da6mW#F31

Opinions on this? This is just a clean install from the package and framework. So curious to see how people handle for this or if we can have a solution. Hope this makes sense if not let me know.

**Comment by lloy0076** [comment]
I used a Laravel 6 installation, and setup Airlock.

I go to:

> curl --location --request GET 'http://laravel-playground.test/api/user' \
--header 'Authorization: Bearer hFiORTL2G9LAFQjn3b4rKadJZ1tFuJPUlkjIAr29rhngJqUbbImmN2FYTDcJrNjdpffpdXKWY1IEnDig '

And get:

```
{
    "id": 1,
    "name": "David Lloyd",
    "email": "lloy0076@adam.com.au",
    "email_verified_at": null,
    "created_at": "2019-08-24 00:28:59",
    "updated_at": "2019-12-28 11:58:54"
}
```

Which is precisely what I expect...

**Comment by lloy0076** [comment]
If I remove the authorisation header I get a dump of the Login page (as HTML) which is also what I'd expect.

**Comment by koenhoeijmakers** [comment]
This is not an Airlock issue, this has something to do with the `Authenticate` middleware which defaults to a redirect to the `login` route, you're free to change the default to your needs.

**Comment by narwy** [comment]
@lloy0076 thats correct but if you don’t have a login page and use laravel as a api only solution for your spa and someone accessed that route from their browsers it defaults to a 500 error. Sentry and other tools love this.

@koenhoeijmakers it’s because the Authenticate class has the expectsJson statement, if not being the redirect to Login. But that shouldn’t be a default option. Passport has this same issue also. But I’m questioning it within Airlock now to see if it’s something we can fix going forward.

**Comment by driesvints** [comment]
Passing the accept header is required to let the logincontroller return a json response.

**Comment by narwy** [comment]
@driesvints That's correct but if you do a clean install of laravel + require this package then visit the example route without the header you get a 500 error.

**Comment by dillingham** [comment]
@driesvints was wondering this too. Maybe the airlock middleware can set it 🤔

**Comment by dillingham** [comment]
@narwy had this issue too.. easy fix is to update `app/Http/Middlewares/Authenticate.php`

```php
protected function redirectTo($request)
{
    if($request->is('api/*')) {
        abort(401, 'Access denied');
    }

    if (! $request->expectsJson()) {
        return route('login');
    }
}

**Comment by dillingham** [comment]
Wondering if having a middleware add it for api routes makes sense 🤔 
```php
public function handle($request, Closure $next)
{
    $request->headers->set('accept', 'application/json', true);

    return $next($request);
}
```

**Comment by driesvints** [comment]
@dillingham I don't think it's wise to solve this with a middleware. API consumers should pass the correct headers.

**Comment by dillingham** [comment]
@driesvints yeah you're right :) probably best to just add `withHeaders` in `setUp`
