### ISSUE TITLE
[Feature Request] Expiration based off token name

### ISSUE THREAD

**Issue by narwy** [laravel/airlock#73]
Allow the expiration option to accept an array of the token names so you can set specific timeouts based on type of token. Web app, mobile app etc.

You could've the ability to set the config like this:
```
'expiration' => [
    'token-name' => null,
    'web-app' => null,
    'mobile-app' => null,
],
```

**Comment by narwy** [comment]
@taylorotwell How do you feel for this? If you're happy with it I can go ahead and do a PR for this functionality.

**Comment by taylorotwell** [comment]
Using token names doesn't make any sense? The names are user provided?

**Comment by narwy** [comment]
@taylorotwell But you can do `$user->createToken('token-name')`.. so if you create a token to be mobile app related you can specify a timeout for that compared to a web app which could be a public device. The ability to set expiry on specific tokens seems like a basic form of functionality it should support?
