### ISSUE TITLE
Add prefix key to config file

### ISSUE THREAD

**Issue by jurrid** [laravel/airlock#74]
In this [commit](https://github.com/laravel/airlock/commit/ae558c432c207c8a46e3d30e82e6971e23478971) @taylorotwell  added the prefix option for the airlock routes.

I personally add the prefix `api` to all my api calls.

A small but helpful enhancement would be to add to prefix key to the config file by default!

Below a snipped for the config file.
```php
/*
|--------------------------------------------------------------------------
| Airlock Route Prefix
|--------------------------------------------------------------------------
|
| This is the place to add a prefix to the Airlock routes. Feel free to
| change the default prefix to anything you like. For example to add api
| prefix before every api call made to Airlock routes
|
*/

'prefix' => 'airlock',

```

**Comment by driesvints** [comment]
Please see https://github.com/laravel/airlock/pull/71

**Comment by alexleeelkins** [comment]
This is clearly something people want, why has it been closed on two separate occasions?
