### ISSUE TITLE
'tokenable_id' cannot be null 

### ISSUE THREAD

**Issue by rehamwalid** [laravel/airlock#75]
I am using airlock for authentication and when i try to create a token it gives me this error 

`Integrity constraint violation: 1048 Column 'tokenable_id' cannot be null (SQL: insert into `personal_access_tokens` (`name`, `token`, `abilities`, `tokenable_id`, `tokenable_type`, `updated_at`, `created_at`) values (admin@email.com, 00f23c417988d8fef36a6275db0a6346acfe6c14004f4bc0d086d9a6249e4e0f, ["*"], ?, Modules\User\Entities\User, 2020-02-18 12:46:10, 2020-02-18 12:46:10))`

Any idea why this happen ?

I am using Laravel Framework 6.15.0

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by shopapps** [comment]
I am experiencing the same issue, could not find anything on the channels you suggested, so have created a new question on stackoverflow:

https://stackoverflow.com/questions/60562572/laravel-airlock-issue-with-creating-tokens-tokenable-id-cannot-be-null

am putting this here just in case others see the same issue and will have somewhere to look.

**Comment by aqaue18ax** [comment]
```
$user->save();
$user->createToken('xxx');
```

**Comment by samuelsennev** [comment]
> ```
> $user->save();
> $user->createToken('xxx');
> ```

I had the same issue. In my case, I forgot to save the user ($user->save()) lol... then, worked.

**Comment by samuelsennev** [comment]
> i have this same error.. 
> 
> how to fix this problem dude?

In my case, I had to save the user before creating his token.

```
$user->save();

//then
$token = $user->createToken("tokenName");
```

**Comment by iamandreadompe** [comment]
For me the error wars my primary key wasn't **id** but **username**,
so i had to set 
`protected $primaryKey = 'username';`

in the model file app/Models/User.php

and everything works well

**Comment by mostafa-rami-1** [comment]
> For me the error wars my primary key wasn't **id** but **username**, so i had to set `protected $primaryKey = 'username';`
> 
> in the model file app/Models/User.php
> 
> and everything works well

thanks it thats works for me

**Comment by NomanJaved** [comment]
I were also struggling with the same issue 

what I were doing wrong was

I have the different table name instead of user -> tw_user

and the problem were I set the user_id as the primary key instead of id. so there were no id column present. 

I rename the user_id with the id and it worked for me. 

Late answer: but may be help someone else.

**Comment by jcfs87** [comment]
i had the same error and worked with
 protected $primaryKey = 'users_id';

**Comment by mashhoodrehman** [comment]
I had the same problem , 
if you are using selected coulmns , it will through error
Replace this 
$user = User::where('email',$loginUserData['email'])
                ->select('name' , 'email','phone' , 'country_code','password')
                ->first();
                to
                $user = User::where('email',$loginUserData['email'])
//                ->select('name' , 'email','phone' , 'country_code','password')
                ->first();
