### ISSUE TITLE
After following the documentation i get unauthenticated message for my auth:airlock routes.     

### ISSUE THREAD

**Issue by Mizan-Rifat** [laravel/airlock#77]
I'm using react preset.login and register work fine but when i use auth:airlock middleware i get unauthenticated message.i have changed my session driver to cookie.still no luck..

**Comment by Mizan-Rifat** [comment]
I'm using react preset.login and register work fine but when i use auth:airlock middleware i get unauthenticated message.i have changed my session driver to cookie.still no luck..

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dominik-wbz** [comment]
Try to set in your env AIRLOCK_STATEFUL_DOMAINS to equal your actual domain

**Comment by ipearx** [comment]
Should be SANCTUM_STATEFUL_DOMAINS now in your .env file
