### ISSUE TITLE
Single Action Controllers ( __invoke() ) constructor not authenticating session

### ISSUE THREAD

**Issue by kharysharpe** [laravel/airlock#78]
- Airlock Version: v0.2.1
- Laravel Version: v6.17.0
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Not sure if I missed something, if it's by design or a bug.

### Steps To Reproduce:

```php
class TestController extends ApiController
{
    public function __construct(Request $request)
    {
        dd($request->user()); // null;
    }

    public function __invoke(Request $request)
    {
        dd($request->user()); // App\User;
    }
}
```

How do i get the signed in user in the constructor?

**Comment by rcubitto** [comment]
It's by design since the session hasn't been loaded yet. Here's a workaround using the middleware helper method.

```php
public function __construct()
{
    $this->middleware(function ($request, $next) {
        $request->user(); // your logic here...

        return $next($request);
    });
}
```

**Comment by kharysharpe** [comment]
It worked, thanks @rcubitto
