### ISSUE TITLE
CSRF Token mismatch subdomain

### ISSUE THREAD

**Issue by roosht3** [laravel/airlock#79]
- Airlock Version: 0.2.1
- Laravel Version: 6.2
- PHP Version: 7.4.2
- Database Driver & Version: Mysql & 8.0.19

I am trying to login using the package and I was successful with Vue running on `laratesting:8080` and `laratesting:8081` it logins, gives the correct csrf tokens and subsequent requests are working fine. What I am trying to achieve,
API: `api.laratesting`
Vue: `app.laratesting`

I am sending a request to laravel from `app.laratesting` to `api.laratesting`. Cookies are returned but not set. 
with SESSION_DOMAIN=.laratesting
> This set-cookie domain attribute was invalid with regards to the current host url
with SESSION_DOMAIN=null
> This set-cookie didn't specify a samesite attribute

Am I doing something wrong or should I stick to access_tokens ?

**Comment by imranrbx** [comment]
I am having the same issue using laravel valet I'm getting 401 unauthorized, but when using PHP artisan serve and using localhost:8000 then same code is working fine, I tried adding l7app.test which is my test domain on laravel valet but it's not working always giving 401 after sending requests to /airlock/csrf-cookie then /api/login.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by michcio1234** [comment]
@roosht3 did you manage to solve it?

**Comment by brandonbronisz** [comment]
This is definitely a bug. Running Sanctum on a subdomain does not work.

**Comment by driesvints** [comment]
@brandonbronisz I can run Sanctum on a subdomain just fine.

**Comment by samwightt** [comment]
Can this issue be reopened? I'm still experiencing this and have tried everything I can think of.

**Comment by driesvints** [comment]
@samwightt please try a support channel.

**Comment by alignwebs** [comment]
If anyone is facing CSRF token mismatch issue, then please try checking if `SANCTUM_STATEFUL_DOMAINS=` is set in `.env` 

When `SANCTUM_STATEFUL_DOMAINS` is not present in ENV then it throws CSRF token mismatch error.

Hope it helps someone. :)

**Comment by roosht3** [comment]
This was due to that I was using nginx headers (for cors). And not specifying the **Always** directive.
