### ISSUE TITLE
not working when column type is uuid

### ISSUE THREAD

**Issue by kunaldodiya** [laravel/airlock#82]
I am using postgres and airlock is not working when column type is uuid

**Comment by driesvints** [comment]
Please fill out the issue template and share steps to reproduce the problem.

**Comment by krunaldodiya** [comment]
> How use Sanctum when User model use uuid (type and PK name uuid) ?
> 
> Changed migration to:
> 
> ```
> 
>       $table->string('tokenable_type');
>       $table->uuid('tokenable_uuid');
> ```
> 
> In User model:
> 
> ```
> 
>    public function tokens()
>     {
>         return $this->morphMany(Sanctum::$personalAccessTokenModel, 'tokenable', "tokenable_type", "tokenable_uuid");
>     }
> ```
> 
> Extend PersonalAccessToken (need for set morph options)
> 
> ```
> 
> namespace App\Models;
> 
> use Laravel\Sanctum\PersonalAccessToken as BasePersonalAccessToken;
> 
> class PersonalAccessToken extends BasePersonalAccessToken
> {
>     public function tokenable()
>     {
>         return $this->morphTo('tokenable', "tokenable_type", "tokenable_uuid");
>     }
> }
> ```
> 
> Then in AppServiceProvider set usePersonalAccessTokenModel
> 
> ```
> 
> namespace App\Providers;
> 
> use App\Models\PersonalAccessToken;
> use Illuminate\Support\ServiceProvider;
> use Laravel\Sanctum\Sanctum;
> 
> class AppServiceProvider extends ServiceProvider
> {
>     /**
>      * Register any application services.
>      *
>      * @return void
>      */
>     public function register()
>     {
>         Sanctum::usePersonalAccessTokenModel(PersonalAccessToken::class);
>     }
> ///....
> }
> ```

thanks i will give it a try

**Comment by alejandrozepeda** [comment]
I'm using UUIDs as the primary key for my User model, the needed change is just export the default migration 

`php artisan vendor:publish --tag=sanctum-migrations`

and change the `tokenable` field to 

`$table->uuidMorphs('tokenable');`

**Comment by abdelhadiyoucef** [comment]
use this in AppServiceProvider
  public function boot()
    {
        Schema::defaultStringLength(191);
    }

**Comment by netojose** [comment]
I fixed doing:

1 - Changing sanctum migration, to:
```php
$table->uuidMorphs('tokenable');
```

2 - Updating User model, adding:
```php
public $incrementing = false;
protected $casts = ['id' => 'string'];
```
