### ISSUE TITLE
Mark Laravel 6.* dependency to 6.9.0 or higher

### ISSUE THREAD

**Issue by peterfox** [laravel/airlock#88]
I just tried to install Airlock into a project that was on 6.3.0 and found it didn't work. Having looked into the issue Airlock requires at least [6.9.0](https://github.com/laravel/framework/releases/tag/v6.9.0) to work due to the use of `\Illuminate\Foundation\Http\Kernel::prependToMiddlewarePriority();` in `Laravel\Airlock\Air\AirlockServiceProvider::configureMiddleware()` on line 109.

I would suggest that the composer json be updated or that a check be added for lower versions without the method to avoid calling it and making it clear in a doc that anything pre 6.9.0 requires the middleware to be assigned manually.

Happy to make the changes myself and PR them it's agreed to be worthwhile.

**Comment by driesvints** [comment]
@peterfox definitely, feel free to send in a pr.

**Comment by peterfox** [comment]
@driesvints what's your preference, change composer.json or just ignore kernel modification for pre 6.0.9?

**Comment by driesvints** [comment]
Update composer.json
