### ISSUE TITLE
Add support to disable update the last used

### ISSUE THREAD

**Issue by alinalexandru** [laravel/airlock#91]
### Motivation
On environment with many requests, updating the last used field at every requests adds a lot of load on database. Especially when you have a master slave replication.
In our scenario that field is not used at all.

By disabling the update we gain 20% more throughput 
```php
return $this->supportsTokens($accessToken->tokenable) ? $accessToken->tokenable->withAccessToken(
                //tap($accessToken->forceFill(['last_used_at' => now()]))->save()
                $accessToken
            ) : null;
```
I am not a Laravel developer, so I can't submit a PR.

**Comment by driesvints** [comment]
No plans on changing this ourselves but anyone else is free to send in a pr.

**Comment by CrazyFreeMan** [comment]
I think a good option is to add something like config ("sanctum.tap_last_used_at", true) and then check in Guard

**Comment by LINKeRxUA** [comment]
> I think a good option is to add something like config ("sanctum.tap_last_used_at", true) and then check in Guard

Exactly! Using of config file, binding classes with contracts injection can improve ability to change behaviour by own implementation! Especially if you are using db replications.

**Comment by myckhel** [comment]
push request submitted for the issue.

**Comment by alexqem** [comment]
@alinalexandru  could you please describe for noobies how to do it?
Also have the same problem

**Comment by alinalexandru** [comment]
In my example, I have created a patch that commented the line 
`tap($accessToken->forceFill(['last_used_at' => now()]))->save()`

**Comment by mostafaznv** [comment]
You can use it on your own.

1. Create your custom model for `PersonalAccessToken`:
```php
<?php

namespace Support\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Laravel\Sanctum\PersonalAccessToken as SanctumPersonalAccessToken;


class PersonalAccessToken extends SanctumPersonalAccessToken
{
    protected function lastUsedAt(): Attribute
    {
        return Attribute::make(
            set: function (mixed $value): void {
                // disable updating the last_used_at attribute as it's not used

                return;
            },
        );
    }
}
```

2. Register it in  `AppServiceProvider`
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Laravel\Sanctum\Sanctum;
use Support\Models\PersonalAccessToken;


class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Sanctum::usePersonalAccessTokenModel(PersonalAccessToken::class);
    }
}

```

**Comment by MElkmeshi** [comment]
I made a PR for this feature https://github.com/laravel/sanctum/pull/583
