### ISSUE TITLE
using multiple frontend spa with single backend.

### ISSUE THREAD

**Issue by rohan-khatri** [laravel/airlock#93]
- Airlock Version: 1.0
- Laravel Version: 6.2
- PHP Version: 7.2
- Database Driver & Version: mysql@5.7

### Description:
i want to use same backend for multiple spa. (multiple domain).
if, user loggedIn for "one.domain.test" then if user visits "two.domain.test", then user also get loggedIn in another domain.

**Comment by liamkeily** [comment]
I'm currently dealing with a similar issue. In your case setting [SESSION_DOMAIN](https://github.com/laravel/laravel/blob/master/config/session.php#L156)
 to one.domain.test may help.

For me i am using one.domain.test and one-api.domain.test and i believe i'll need to move the api to api.one.domain.test to get this working nicely.

**Comment by driesvints** [comment]
Atm no plans but if you can implement this cleanly a PR maybe accepted by Taylor
