### ISSUE TITLE
Session expired early than the session lifetime value.

### ISSUE THREAD

**Issue by dluague** [laravel/airlock#95]
- Airlock Version: 1.0.0
- Laravel Version: 6.18.0
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 5.7.9

### Description:
After adding a new item to the session it will be deleted after a few minutes even if my session lifetime is set to 120. 

### Steps To Reproduce:
1. Add a new item to the session using:
```php
session()->put('key', 'value');
```
2. After a few minutes the new item is gone.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
